### ISSUE TITLE
Facility captures on Indar outside of the "T Meta" 

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstrome26/PS2Alerts#21]
So we all know Indar has a T like shape to activity on the continent, it might be good to know which facilities are classed as being within the T, and provide metrics on those, such as captures for bases in and out of the T.

**Comment by jtheis85** [comment]
Given Xander's pending rework of Indar that's specifically designed to reduce the impact of the "T", might want to hold off on this.

**Comment by Maelstromeous** [comment]
That's a good point, it's a feature slated for the future.

**Comment by Maelstromeous** [comment]
Closing, not really feasible with time constraints.
