### ISSUE TITLE
Alert #20430 incorrectly attributed to TR, should be "Draw"

### ISSUE THREAD

**Issue by ghost** [Maelstrome26/PS2Alerts#47]
I was in this alert and it was a draw. The statistics show 33% Vanu, 31% NC and 33% TR. One TR territory was disconnected during this alert, may have affected the outcome in this one.

http://www.ps2alerts.com/alert/20430

**Comment by Maelstromeous** [comment]
Draws are a known bug, it's a websocket issue. I've already logged it under https://github.com/Maelstrome26/ps2alerts-ws/issues/26

**Comment by Maelstromeous** [comment]
I'll see if I can take a look at it sometime today.

**Comment by Maelstromeous** [comment]
Did this alert result in a continent lock by any chance?

**Comment by Maelstromeous** [comment]
This has now been fixed. I've added in a more reliable way of calculating results. It now also properly takes VP victories into account.
