### ISSUE TITLE
Player / Outfit Profiles

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstrome26/PS2Alerts#49]
Idea's been brewing in my head for some time now.

The ultimate user experience is to be able to see their own impact in the game. To this end, I believe User profiles will be the best way to do this.

E.g. A user can search for themselves or another player and see their statistics across the board, such as how many alerts they've been involved in, how many kills have been recorded for them, etc.

Same can go for outfits.
# Players
- Total Kills
- Total Deaths
- Total TKs
- Total Suicides
- Total Headshots
- Number of Alerts participated
- Using above, KPA and DPA
- Weapon Statistics
  - Kills per weapon
  - TKs per weapon
  - Headshots per weapon
- Vehicle Statistics
- List of all alerts participated, along with basic metrics (kills, deaths, K/D), which will link them to the actual alert itself.
- XP Types (with ribbons)
  - Revives
  - Heal
  - Repairing

Census Info: https://census.daybreakgames.com/get/ps2:v2/character/5428010618035323201?c:resolve=stat,stat_by_faction
# Outfits
- Total Kills
- Total Deaths
- Total TKs
- Total Suicides
- Total Members
- Number of Alerts participated (may have to somehow restrict this to prevent 1 man alerts always contributing to this metric
- KPA and DPA
- List of members, showing all their statistics (this will have to be heavily cached)
- List of all alerts participated, along with basic metrics)

**Comment by Maelstromeous** [comment]
Updated OP with things I'd like to have on these pages.

**Comment by Pattyfathead** [comment]
This is a great feature.  I will definitely use it.  Thanks!

**Comment by Maelstromeous** [comment]
Ribbons:

Use of ribbons would be very useful here to gauge statistics such as Revives etc. 

Census link: https://census.daybreakgames.com/get/ps2:v2/achievement?c:limit=100000

Example Asset: https://census.daybreakgames.com/files/ps2/images/static/8338.png

Although currently no mention of Revive ribbons. Will have to dig deeper unless someone is able to find it out.

**Comment by Maelstromeous** [comment]
First iteration of Player Profiles Launched.

More details: https://www.reddit.com/r/Planetside/comments/4g9zfo/ps2alerts_player_profiles_change_log_update/

**Comment by Maelstromeous** [comment]
Fully completed. Player Profiles and Outfit Profiles are now live as of 29/04/16.
