### ISSUE TITLE
Real Time Alert Monitor broken since March 11th from 07:00 CET

### ISSUE THREAD

**Issue by ghost** [Maelstrome26/PS2Alerts#50]
It's not showing any alerts since March 11th from 07:00 CET and on.

**Comment by Maelstromeous** [comment]
Yup, it's a middleman API issue, there's literally nothing I can do about it right now. The developer is in AUS timezones, which is like 4AM there right now.

**Comment by Maelstromeous** [comment]
Thanks for the report though :-)

**Comment by ghost** [comment]
Then the waiting game begins...

**Comment by Maelstromeous** [comment]
He'll be up soon hopefully.

**Comment by Maelstromeous** [comment]
Service resumed at around 5:00 GMT.
