### ISSUE TITLE
https://github.com/php-pm/php-pm

### ISSUE THREAD

**Issue by kurtextrem** [Maelstrome26/PS2Alerts#51]
https://github.com/php-pm/php-pm
Maybe this is something interesting for you? :)

**Comment by Maelstromeous** [comment]
I'm not using PHP any more with PS2Alerts' frontend, it's all a javascript single page app now. Although, it does look interesting, might be useful for the PHP based API :-)

**Comment by kurtextrem** [comment]
Oh I see. :D
