### ISSUE TITLE
Would it be possible to bring back Alert population statistics?

### ISSUE THREAD

**Issue by Pattyfathead** [Maelstrome26/PS2Alerts#52]
Hey Maelstrome,

I realize you still have lots of plans for the new and improved PS2alerts, I was just wondering if this feature would be making a comeback.  Since VPs came to be, and people can just switch factions in the last few minutes of an alert, it seems 4th factioning is a major issue again.  It would be great to see the population throughout the alert, like the previous version of PS2 Alerts.  Previously it was real-time, and that is not at all necessary.  If even it pulled the population every 10 minutes, that would give us plenty of info on how the population played out throughout an alert.

Thanks for all the hardwork, it is by far my most used Planetside 2 related site!

**Comment by Maelstromeous** [comment]
It's next on my list for alert page updates, I'm focusing on doing the profiles right now so we can expand the history of a player. Right now, if you want to look at your own participation, you have to catch the alert in the currently set 48 hour window for the alert history. 

I've got some research to do regarding the graphing library that I used for the older version of the site, and whether it's compatible with Angular (it should be, I just need to figure it out). Once I've done that, a lot of doors unlock, especially for the Homepage which is very sparse of stats right now. 

I need said graphing library to properly represent the population changes over time. I don't believe having averages will cut it, although I can always chuck that in too.

**Comment by Maelstromeous** [comment]
This is still a priority. However, due to the middleman API not sending population information isn't not as high as it once was. I'll have to work with Jhett to reinstate Population metrics.
