### ISSUE TITLE
Alert Notification Sound

### ISSUE THREAD

**Issue by jo-bert** [Maelstrome26/PS2Alerts#53]
You should create notification for users everytime an alert is approaching,so users who want to play only during alert knows.
**For reference**:
http://deathsnacks.com/wf/index.html

**Comment by Maelstromeous** [comment]
Unfortunately we have no way of knowing if an alert is about to start, we only know that one has triggered.

It has crossed my mind that I could play a sound when an alert started on the site, but I'd imagine that would get very annoying very quickly.

**Comment by jo-bert** [comment]
Ah ok. Thanks for answering!
