### ISSUE TITLE
Territory control tracking is incorrect

### ISSUE THREAD

**Issue by Pattyfathead** [Maelstrome26/PS2Alerts#60]
Picture is attached.  Fisu's alert tracking is off as well, which makes me think it might be a problem on DBGs end.  Just wanted you to be aware of it.  This is a picture of my three screens.  As you can see its tracking the alert correctly.  But it shows that TR have no territory control.  In reality all factions control a similar amount of territory.

![problem tracking territory](https://cloud.githubusercontent.com/assets/17971820/14921178/1c8a2a0a-0dee-11e6-8c11-9dde8acd90ba.png)

**Comment by Maelstromeous** [comment]
I'll let the DBG API team know. Cheers for the report. In the interim I'll disable alert tracking to prevent further contamination of the resultset.

**Comment by Maelstromeous** [comment]
It appears fisu has reported this issue also. The dev team are aware.

**Comment by Maelstromeous** [comment]
Awaiting fix from DBG API team. Hands are tied until this is done.

**Comment by Maelstromeous** [comment]
They've finally fixed it, however Indar is still broken as the bases they removed haven't been updated in the API. I've disabled tracking for Indar for now.

**Comment by Maelstromeous** [comment]
This should be corrected and has been running normally for a while now. Please reopen if it goes wonky again.
