### ISSUE TITLE
Kills and other stats aren't accurate.

### ISSUE THREAD

**Issue by Shadowdoom8000** [Maelstrome26/PS2Alerts#72]
Every time I play planetside 2 I check my kills after wards and it only moves up one kill every time I play. Sometimes it doesn't change at all.
Still a great website though.

**Comment by Shadowdoom8000** [comment]
#71 goes with #72

**Comment by Maelstromeous** [comment]
Hi Shadowdoom,

Thanks for the report. I'll have a look at it some point this weekend probably, the fix has been well overdue.

**Comment by Shadowdoom8000** [comment]
Ok, thanks for the update. Also I really find the website helpful. thanks
again.

**Comment by Shadowdoom8000** [comment]
I find it very helpful to have a website that includes the ps4 servers.

**Comment by Maelstromeous** [comment]
This has now been fixed. Please reopen the issue if it appears again.
