### ISSUE TITLE
Outfits and servers

### ISSUE THREAD

**Issue by rafamem** [Maelstrome26/PS2Alerts#74]
Hello! The followed outfits are from Genudine (PS4 US) not from Miller:

http://www.ps2alerts.com/profiles/outfit/37533427458382531

http://www.ps2alerts.com/profiles/outfit/37534205255888743

http://www.ps2alerts.com/profiles/outfit/37534923133322586

http://www.ps2alerts.com/profiles/outfit/37535059393448407

http://www.ps2alerts.com/profiles/outfit/37534923133360458

http://www.ps2alerts.com/profiles/outfit/37536033136707474

Also, in Genudine:

Suicide Latin Squad = LSS
Vanu Latino = VSLA
TerranHispanohablantes = THHO
Vanu Boricua Division = VBD

Those listed in Miller do not appear in this ranking: http://www.ps2alerts.com/leaderboards

**Comment by Maelstromeous** [comment]
My apologies but this project​ is no longer actively supported due to lack of personal time. Sorry :(

**Comment by rafamem** [comment]
Too bad, it's a good project. :-(
