### ISSUE TITLE
Only Ceres and Genudine servers alerts are registered

### ISSUE THREAD

**Issue by ManuelPhelouzat** [Maelstrome26/PS2Alerts#90]
Great site ! Cool metrics, thank you for the time you invest in this great tool.

Now the bug :
Since Critical Mass update, only Ceres and Genudine servers alert are registered... 
As I'm from Cobalt, it bother me a bit...

**Comment by Maelstromeous** [comment]
I'm painfully aware but I'm struggling to find the proper free time to make the system work again. I might have some time next week but I can't promise anything right now.

**Comment by ProsvetNC** [comment]
Russian community is looking forward when will work the website.
Thank You!!!

**Comment by Maelstromeous** [comment]
I'm going to try and get it fixed over the next couple of days.

**Comment by Maelstromeous** [comment]
Progress with the websocket collection code has been made. I'm encountering some bugs regarding collecting combat statistics but at least alerts are being recorded on my development environment.

**Comment by ManuelPhelouzat** [comment]
Thank you ! It's great to have this tool back ! ;)
