### ISSUE TITLE
Request : usefullness of fights

### ISSUE THREAD

**Issue by ManuelPhelouzat** [Maelstrome26/PS2Alerts#91]
I have an idea for a new stat : 
How much of the fight was actually useful for the alert.

Example : It's a TR alert, the goal for TR is to maintain territory and the goal of VS and NC is to prevent the TR to win by getting their territory back.
So the VS vs NC fights are "useless", they do not contribute to the alert goals.

Do you think it's a good idea ?

**Comment by Maelstromeous** [comment]
They do contribute as alert goals as they can over take the faction that triggered the alert and win.

**Comment by ManuelPhelouzat** [comment]
Oh, I haven't thought of that. You are right. Well let's cancel this ticket :p
