### ISSUE TITLE
Constantly disconnected

### ISSUE THREAD

**Issue by VoRGoR** [Maelstrome26/PS2Alerts#92]
![unsure](https://user-images.githubusercontent.com/8906373/45808443-b8332300-bcbd-11e8-8037-2a95348633c8.PNG)
I'm not disconnected from the internet, and i'm not sure how to solve this. I realise a github issue isn't really the best place for this but I don't know how else to contact you :/

**Comment by Maelstromeous** [comment]
My apologies, but I'm not maintaining the project any more. Might just take it down to be honest.

Basically the websocket code is very much out of date, using a single javascript while which has 4468 lines of code in it. Unfortunately it's not feasible for me to dedicate any more time to it :(
